from agile_agent_factory.tools.jira_client import JiraClient, make_adf_doc
from agile_agent_factory.tools.jira_facade import JiraFacade
from agile_agent_factory.tools.logger import log
from agile_agent_factory.tools.workflow import WorkflowState


def emulate_deployment(jira: JiraClient, story_keys: list[str], state: dict) -> dict:
    log("Emulated SRE deployment starting.")
    facade = JiraFacade(jira)
    epic_keys = state.get("epic_keys", [])

    facade.move_all(story_keys + epic_keys, WorkflowState.QA)

    report = (
        "CI/CD Pipeline Report (Emulated)\n"
        "─────────────────────────────────\n"
        "Build:               PASS\n"
        "Unit Tests:          PASS\n"
        "Integration Tests:   PASS\n"
        "Deployment:          EMULATED SUCCESS\n"
        "\nGenerated by Agile-Agent-Factory SRE agent."
    )
    for key in story_keys:
        jira.add_comment_adf(key, make_adf_doc(report))
        log(f"Posted deployment report to {key}.")

    facade.move_all(story_keys, WorkflowState.DONE)
    facade.move_all(epic_keys, WorkflowState.DONE)
    facade.move_all(list(state.get("subtasks", {}).values()), WorkflowState.DONE)

    return {"status": "DONE", "current_phase": "release_done"}
