from agile_agent_factory.tools.jira_client import JiraClient, make_adf_doc
from agile_agent_factory.tools.logger import log


def emulate_deployment(jira: JiraClient, story_keys: list[str], state: dict) -> dict:
    log("Emulated SRE deployment starting.")
    epic_keys = state.get("epic_keys", [])

    for key in story_keys + epic_keys:
        try:
            jira.transition_issue(key, "QA")
        except ValueError as e:
            log(str(e))

    report = (
        "CI/CD Pipeline Report (Emulated)\n"
        "─────────────────────────────────\n"
        "Build:               PASS\n"
        "Unit Tests:          PASS\n"
        "Integration Tests:   PASS\n"
        "Deployment:          EMULATED SUCCESS\n"
        "\nGenerated by Agile-Agent-Factory SRE agent."
    )
    for key in story_keys:
        jira.add_comment_adf(key, make_adf_doc(report))
        log(f"Posted deployment report to {key}.")
        try:
            jira.transition_issue(key, "Done")
            log(f"Transitioned {key} to Done.")
        except ValueError as e:
            log(str(e))

    for epic_key in epic_keys:
        try:
            jira.transition_issue(epic_key, "Done")
            log(f"Transitioned Epic {epic_key} to Done.")
        except ValueError as e:
            log(str(e))

    for subtask_key in state.get("subtasks", {}).values():
        try:
            jira.transition_issue(subtask_key, "Done")
            log(f"Transitioned Subtask {subtask_key} to Done.")
        except ValueError as e:
            log(str(e))

    return {"status": "DONE", "current_phase": "release_done"}
